openapi: 3.0.1
info:
  description: |
    Automatic translation Diary
  version: "1.0.0"
  title: Automatic Translation Diary

paths:
  /diaries/{lang}:
    post:
      summary: 日記を書く
      parameters:
        - name: lang
          in: path
          required: true
          type: string
      requestBody:
        description: 日記
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  type: string
                  example: 本日は晴天なり
      responses:
        '201':
          description: Creaed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diary'
  /diaries:
    get:
      summary: 日記の一覧を取得する
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Diary'
  /diaries/{diaryId}/speech/{lang}:
    get:
      summary: 日記の読み上げデータを取得する
      parameters:
        - name: diaryId
          in: path
          required: true
          type: string
        - name: lang
          in: path
          required: true
          type: string
components:
  schemas:
    Diary:
      type: object
      properties:
        id:
          type: string
          example: 8f9ef105-2d09-4925-9a76-4754a378ebab
        lang:
          type: string
          enum: [Ja, En]
        note:
          type: string
          example: 本日は晴天なり
        postedAt:
          type: string
          example: "2020-07-19T17:11:40+09:00"
